import Head from "next/head";
import Layout from "../components/Layout";
import styles from "../styles/Home.module.css";
import HomeMain from "../components/Home/HomeMain";
import React, { useState } from "react";
import Image from "next/dist/client/image";
import styled from "styled-components";

const BackIMG = styled.div`
  position: absolute;
  opacity: 0.03;
  top: 150px;
  left: 1100px;
`;

export default function Home() {
  const [tabsNav, setTabsNav] = useState("home");
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        {/* eslint-disable-next-line */}
        <link
          href="https://fonts.googleapis.com/css2?family=Oswald:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        {/* eslint-disable-next-line */}
        <link
          href="https://fonts.googleapis.com/css2?family=Anton&family=Oswald:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main className={styles.main}>
        <Layout tabsNav={tabsNav} setTabsNav={setTabsNav}>
          <HomeMain tabsNav={tabsNav} setTabsNav={setTabsNav}/>
        </Layout>
        <BackIMG>
          <Image
            src={"/images/Gaucho.png"}
            alt="gaucho bg"
            width={601}
            height={768}
          />
        </BackIMG>
      </main>
    </div>
  );
}
