import Head from "next/head";
import Layout from "../components/Layout";
import styles from "../styles/Home.module.css";
import HomeMain from "../components/Home/HomeMain";

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        {/* eslint-disable-next-line */}
        <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@400;500;700&display=swap" rel="stylesheet"/>
      </Head>

      <main className={styles.main}>
        <Layout>
          <HomeMain />
        </Layout>
      </main>
    </div>
  );
}
